export const TESTIMONIALS_DATA = [
  {
    name: 'Omar Hassan',
    role: 'HIT Athlete',
    location: 'New Cairo',
    program: 'HIT Egypt Membership',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    beforeAfter: {
      before: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
      after: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop'
    },
    verified: true,
    quote: 'HIT Egypt changed everything for me. The community, the energy, the coaches — I have never felt so motivated. Over a year in and I am still coming back every single day.',
    result: '15kg weight loss, 40% endurance improvement',
    metrics: { weightLoss: '15kg', endurance: '+40%', duration: '1+ year' },
    rating: 5
  },
  {
    name: 'Nour El-Din',
    role: 'HIT Athlete',
    location: 'El Shorouk',
    program: 'Sweat45 + Perform',
    image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    videoUrl: null,
    beforeAfter: null,
    verified: true,
    quote: 'I started with Sweat45 not knowing what to expect. Now I am doing Perform sessions and running Hyrox races. The progression HIT built for me is incredible.',
    result: 'Completed first Hyrox race in 1:45:30',
    metrics: { raceTime: '1:45:30', progression: 'Sweat45→Perform', achievement: 'Hyrox finisher' },
    rating: 5
  },
  {
    name: 'Kareem Youssef',
    role: 'Corporate Wellness Client',
    location: 'Multiple Locations',
    program: 'Corporate Wellness Program',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
    videoUrl: null,
    beforeAfter: null,
    verified: true,
    quote: 'We enrolled our team in HIT\'s Corporate Wellness program and the results have been outstanding — better energy, stronger team culture, and everyone genuinely enjoys the sessions.',
    result: '30% reduction in health insurance claims',
    metrics: { claimsReduction: '30%', teamEngagement: 'High', healthScore: '+25%' },
    rating: 5
  },
  {
    name: 'Aisha Mohamed',
    role: 'Transformation Success',
    location: 'Zamalek',
    program: 'Hyper45 → Perform',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    videoUrl: null,
    beforeAfter: {
      before: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
      after: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop'
    },
    verified: true,
    quote: 'As a beginner, I was intimidated by fitness. HIT\'s Hyper45 classes are beginner-friendly and the coaches make you feel supported from day one. I\'ve never been more confident!',
    result: '20kg weight loss, progressed to Perform',
    metrics: { weightLoss: '20kg', confidence: '+90%', duration: '6 months' },
    rating: 5
  },
  {
    name: 'Ahmed El-Sayed',
    role: 'Performance Athlete',
    location: 'New Capital',
    program: 'Prymal Sessions',
    image: 'https://images.unsplash.com/photo-1519125602292-46f9f5e9767c?w=400&h=400&fit=crop',
    videoUrl: null,
    beforeAfter: null,
    verified: false,
    quote: 'Prymal sessions completely transformed my training. The intensity, the programming, the expert coaching — this is professional-grade fitness delivered perfectly. Best decision ever.',
    result: '25% strength increase, faster recovery times',
    metrics: { strengthGain: '+25%', recovery: '-30%', benchPress: '+45lbs' },
    rating: 5
  },
  {
    name: 'Layla Mansour',
    role: 'Pilates & Sculpt Member',
    location: 'Heliopolis',
    program: 'Women\'s Sculpt Program',
    image: 'https://images.unsplash.com/photo-1441883943e55-08b4e19c8e8f?w=400&h=400&fit=crop',
    videoUrl: null,
    beforeAfter: null,
    verified: true,
    quote: 'The Sculpt sessions designed specifically for women are amazing. I see real results, feel stronger than ever, and the ladies-only format makes it special and comfortable.',
    result: 'Toned physique, 6kg weight loss, core strength doubled',
    metrics: { weightLoss: '6kg', coreStrength: '+100%', bodyfat: '-8%' },
    rating: 5
  },
  {
    name: 'Mohamed Ashraf',
    role: 'Calisthenics Enthusiast',
    location: 'Maadi',
    program: 'Calisthenics Mastery',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    videoUrl: null,
    beforeAfter: null,
    verified: true,
    quote: 'The Calisthenics program taught me proper form and progressions I never thought possible. From zero pull-ups to multiple sets. The coaches are incredibly knowledgeable.',
    result: '10 consecutive pull-ups, mastered handstand hold',
    metrics: { pullUps: '0→10', skill: 'Handstand', duration: '4 months' },
    rating: 5
  },
  {
    name: 'Yasmin Khalil',
    role: 'Teen Program Graduate',
    location: 'Mohandessin',
    program: 'Teen Fitness Program',
    image: 'https://images.unsplash.com/photo-1507072957ccc-4f65a92e7835?w=400&h=400&fit=crop',
    videoUrl: null,
    beforeAfter: null,
    verified: false,
    quote: 'The Teen program at HIT got me into fitness early. The trainers are awesome, the vibe is positive, and I\'ve made lifelong friends here. Plus, I\'m way stronger than my peers!',
    result: 'Top fitness among peers, improved focus and grades',
    metrics: { strength: 'Top tier', grades: '+15%', community: 'Lifelong friends' },
    rating: 5
  },
  {
    name: 'Fatima Al-Rashid',
    role: 'Senior Wellness Member',
    location: 'Nasr City',
    program: 'Senior Wellness Program',
    image: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
    videoUrl: null,
    beforeAfter: null,
    verified: true,
    quote: 'At 58, I thought my fitness days were behind me. HIT\'s Senior Wellness program proved me wrong. I\'m stronger, more flexible, and I have so much more energy for my grandchildren!',
    result: 'Improved mobility by 45%, maintained active lifestyle',
    metrics: { mobility: '+45%', flexibility: '+35%', age: '58', energy: '+60%' },
    rating: 5
  },
  {
    name: 'Hassan El-Masry',
    role: 'BoxFit Competitor',
    location: '6th of October',
    program: 'BoxFit Competition Track',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop',
    videoUrl: null,
    beforeAfter: null,
    verified: true,
    quote: 'Switched to HIT\'s BoxFit program and my performance skyrocketed. The conditioning, the technique refinement, the mental toughness — this is championship-level training accessible to everyone.',
    result: 'Won 3 amateur boxing tournaments, 8-week transformation',
    metrics: { tournaments: '3 wins', timeframe: '8 weeks', conditioning: '+50%' },
    rating: 5
  },
  {
    name: 'Sara Mansour',
    role: 'PostNatal Recovery Member',
    location: 'Maadi',
    program: 'PostNatal Recovery Program',
    image: 'https://images.unsplash.com/photo-1441883943e55-08b4e19c8e8f?w=400&h=400&fit=crop',
    videoUrl: null,
    beforeAfter: null,
    verified: true,
    quote: 'After childbirth, I was worried I\'d lost my fitness. HIT\'s PostNatal program is specifically designed for mums like me. I regained my strength and confidence, and the community of mums is incredible.',
    result: '12kg postpartum weight loss, restored core strength',
    metrics: { weightLoss: '12kg', recovery: '100%', coreStrength: '+85%' },
    rating: 5
  }
];
